In [1]:
import numpy as np

alist = [1,2,3,4,5]
narray = np.array([1,2,3,4])

In [2]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))


[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
npmatrix1 = np.array([narray,narray,narray]) #matrix with arrays
npmatrix2 = np.array([alist,alist,alist]) #matrix with list
npmatrix3 = np.array([narray,[1,1,1,1],narray]) #matrix with both

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [6]:
okmatrix = np.array([[1,2],[3,4]]) #define 2X2

print(okmatrix)
print(okmatrix*2)




[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [7]:
badmatrix = np.array([[1,2],[3,4],[5,6,7]]) #define a matrix. Note the third row contains 3 elements.

print(badmatrix)
print(badmatrix * 2)



[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [8]:
#scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1 #for each element in the matrix, multiply by 2 and add 1
print(result)

[[3 5]
 [7 9]]


In [9]:
#Add two sum compatible matrices
result1 = okmatrix + okmatrix
print(result1)

#Subtract two sum compatible matrices. this is called difference vector
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [10]:
result = okmatrix * okmatrix #multiply each element by itself
print(result)

[[ 1  4]
 [ 9 16]]


In [11]:
#Transpose a matrix
matrix3x2 = np.array([[1,2],[3,4],[5,6]]) #Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Tranposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Tranposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [12]:
nparray = np.array([1,2,3,4]) #Define an array
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [13]:
nparray = np.array([[1,2,3,4]]) #Define a 1x4 matrix, Note that 2 level of square braces
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]




---


# ***Exercise Begins From Here***

---




In [14]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [15]:
import numpy as np
import pandas as pd

In [16]:
# two matrics
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [17]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.19683462 0.74957622 0.63465865 0.55830291]
 [0.53226348 0.56796304 0.70995006 0.65540212]
 [0.60138802 0.23208347 0.46628087 0.53631562]]


In [18]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 81 -33]
 [ 79 -39]]


In [19]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[81, -33], [79, -39]]


In [20]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

5.333333333333333


In [23]:
main_data = pd.read_csv("/content/mtcars.csv")

In [24]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
